# Generated by Django 5.0.6 on 2024-07-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('letter', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('v', 'V'), ('d', 'D')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('third_name', models.CharField(max_length=60, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('sinf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.sinf')),
            ],
        ),
    ]
