# Generated by Django 5.0.6 on 2024-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ball',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
